package com.smartkyc.dao;
import com.smartkyc.database.ConnectionFactory;
import com.smartkyc.model.AuditLog;
import java.sql.*;
import java.util.*;
import java.util.logging.*;
public class AuditLogDAOImpl implements AuditLogDAO {
    private static final Logger logger=Logger.getLogger(AuditLogDAOImpl.class.getName());
    @Override public boolean insert(AuditLog log){String sql="INSERT INTO audit_logs(user_id,action,module,description)VALUES(?,?,?,?)";try(Connection c=ConnectionFactory.getConnection();PreparedStatement ps=c.prepareStatement(sql)){if(log.getUserId()>0)ps.setInt(1,log.getUserId());else ps.setNull(1,Types.INTEGER);ps.setString(2,log.getAction());ps.setString(3,log.getModule());ps.setString(4,log.getDescription());return ps.executeUpdate()>0;}catch(SQLException e){logger.log(Level.SEVERE,"insert",e);}return false;}
    @Override public List<AuditLog> findAll(){List<AuditLog> l=new ArrayList<>();String sql="SELECT a.*,u.username FROM audit_logs a LEFT JOIN users u ON a.user_id=u.user_id ORDER BY a.created_at DESC";try(Connection c=ConnectionFactory.getConnection();Statement s=c.createStatement();ResultSet rs=s.executeQuery(sql)){while(rs.next())l.add(map(rs));}catch(SQLException e){logger.log(Level.SEVERE,"findAll",e);}return l;}
    @Override public List<AuditLog> findByFilters(String search,String module,String action){List<AuditLog> l=new ArrayList<>();StringBuilder sql=new StringBuilder("SELECT a.*,u.username FROM audit_logs a LEFT JOIN users u ON a.user_id=u.user_id WHERE 1=1");List<String> params=new ArrayList<>();if(search!=null&&!search.isEmpty()){sql.append(" AND (a.description LIKE ? OR u.username LIKE ?)");params.add("%"+search+"%");params.add("%"+search+"%");}if(module!=null&&!module.isEmpty()&&!"All".equals(module)){sql.append(" AND a.module=?");params.add(module);}if(action!=null&&!action.isEmpty()&&!"All".equals(action)){sql.append(" AND a.action=?");params.add(action);}sql.append(" ORDER BY a.created_at DESC");try(Connection c=ConnectionFactory.getConnection();PreparedStatement ps=c.prepareStatement(sql.toString())){for(int i=0;i<params.size();i++)ps.setString(i+1,params.get(i));try(ResultSet rs=ps.executeQuery()){while(rs.next())l.add(map(rs));}}catch(SQLException e){logger.log(Level.SEVERE,"findByFilters",e);}return l;}
    @Override public boolean clearAll(){try(Connection c=ConnectionFactory.getConnection();Statement s=c.createStatement()){s.executeUpdate("DELETE FROM audit_logs");return true;}catch(SQLException e){logger.log(Level.SEVERE,"clearAll",e);}return false;}
    @Override public List<AuditLog> findRecent(int limit){List<AuditLog> l=new ArrayList<>();String sql="SELECT a.*,u.username FROM audit_logs a LEFT JOIN users u ON a.user_id=u.user_id ORDER BY a.created_at DESC LIMIT ?";try(Connection c=ConnectionFactory.getConnection();PreparedStatement ps=c.prepareStatement(sql)){ps.setInt(1,limit);try(ResultSet rs=ps.executeQuery()){while(rs.next())l.add(map(rs));}}catch(SQLException e){logger.log(Level.SEVERE,"findRecent",e);}return l;}
    private AuditLog map(ResultSet rs)throws SQLException{String u=rs.getString("username");if(u==null)u="SYSTEM";return new AuditLog(rs.getInt("log_id"),rs.getInt("user_id"),u,rs.getString("action"),rs.getString("module"),rs.getString("description"),rs.getTimestamp("created_at"));}
}
