package com.smartkyc.dao;
import com.smartkyc.database.ConnectionFactory;
import com.smartkyc.model.User;
import java.sql.*;
import java.util.*;
import java.util.logging.*;
public class UserDAOImpl implements UserDAO {
    private static final Logger logger=Logger.getLogger(UserDAOImpl.class.getName());
    @Override public User findById(int id){String sql="SELECT * FROM users WHERE user_id=?";try(Connection c=ConnectionFactory.getConnection();PreparedStatement ps=c.prepareStatement(sql)){ps.setInt(1,id);try(ResultSet rs=ps.executeQuery()){if(rs.next())return map(rs);}}catch(SQLException e){logger.log(Level.SEVERE,"findById",e);}return null;}
    @Override public User findByUsername(String u){String sql="SELECT * FROM users WHERE username=?";try(Connection c=ConnectionFactory.getConnection();PreparedStatement ps=c.prepareStatement(sql)){ps.setString(1,u);try(ResultSet rs=ps.executeQuery()){if(rs.next())return map(rs);}}catch(SQLException e){logger.log(Level.SEVERE,"findByUsername",e);}return null;}
    @Override public User findByEmail(String email){String sql="SELECT * FROM users WHERE email=?";try(Connection c=ConnectionFactory.getConnection();PreparedStatement ps=c.prepareStatement(sql)){ps.setString(1,email);try(ResultSet rs=ps.executeQuery()){if(rs.next())return map(rs);}}catch(SQLException e){logger.log(Level.SEVERE,"findByEmail",e);}return null;}
    @Override public List<User> findAll(){List<User> list=new ArrayList<>();try(Connection c=ConnectionFactory.getConnection();Statement s=c.createStatement();ResultSet rs=s.executeQuery("SELECT * FROM users ORDER BY user_id DESC")){while(rs.next())list.add(map(rs));}catch(SQLException e){logger.log(Level.SEVERE,"findAll",e);}return list;}
    @Override public List<User> searchUsers(String q){List<User> list=new ArrayList<>();String sql="SELECT * FROM users WHERE username LIKE ? OR full_name LIKE ? OR email LIKE ?";try(Connection c=ConnectionFactory.getConnection();PreparedStatement ps=c.prepareStatement(sql)){String lq="%"+q+"%";ps.setString(1,lq);ps.setString(2,lq);ps.setString(3,lq);try(ResultSet rs=ps.executeQuery()){while(rs.next())list.add(map(rs));}}catch(SQLException e){logger.log(Level.SEVERE,"searchUsers",e);}return list;}
    @Override public boolean insert(User u){String sql="INSERT INTO users(full_name,username,email,password_hash,phone,role,status)VALUES(?,?,?,?,?,?,?)";try(Connection c=ConnectionFactory.getConnection();PreparedStatement ps=c.prepareStatement(sql,Statement.RETURN_GENERATED_KEYS)){ps.setString(1,u.getFullName());ps.setString(2,u.getUsername());ps.setString(3,u.getEmail());ps.setString(4,u.getPasswordHash());ps.setString(5,u.getPhone());ps.setString(6,u.getRole());ps.setString(7,u.getStatus());if(ps.executeUpdate()>0){try(ResultSet k=ps.getGeneratedKeys()){if(k.next())u.setUserId(k.getInt(1));}return true;}}catch(SQLException e){logger.log(Level.SEVERE,"insert",e);}return false;}
    @Override public boolean update(User u){String sql="UPDATE users SET full_name=?,email=?,phone=?,role=?,status=? WHERE user_id=?";try(Connection c=ConnectionFactory.getConnection();PreparedStatement ps=c.prepareStatement(sql)){ps.setString(1,u.getFullName());ps.setString(2,u.getEmail());ps.setString(3,u.getPhone());ps.setString(4,u.getRole());ps.setString(5,u.getStatus());ps.setInt(6,u.getUserId());return ps.executeUpdate()>0;}catch(SQLException e){logger.log(Level.SEVERE,"update",e);}return false;}
    @Override public boolean delete(int id){String sql="DELETE FROM users WHERE user_id=?";try(Connection c=ConnectionFactory.getConnection();PreparedStatement ps=c.prepareStatement(sql)){ps.setInt(1,id);return ps.executeUpdate()>0;}catch(SQLException e){logger.log(Level.SEVERE,"delete",e);}return false;}
    @Override public boolean updateStatus(int id,String s){String sql="UPDATE users SET status=? WHERE user_id=?";try(Connection c=ConnectionFactory.getConnection();PreparedStatement ps=c.prepareStatement(sql)){ps.setString(1,s);ps.setInt(2,id);return ps.executeUpdate()>0;}catch(SQLException e){logger.log(Level.SEVERE,"updateStatus",e);}return false;}
    @Override public boolean resetPassword(int id,String h){String sql="UPDATE users SET password_hash=? WHERE user_id=?";try(Connection c=ConnectionFactory.getConnection();PreparedStatement ps=c.prepareStatement(sql)){ps.setString(1,h);ps.setInt(2,id);return ps.executeUpdate()>0;}catch(SQLException e){logger.log(Level.SEVERE,"resetPassword",e);}return false;}
    @Override public int getTotalUsersCount(){try(Connection c=ConnectionFactory.getConnection();Statement s=c.createStatement();ResultSet rs=s.executeQuery("SELECT COUNT(*) FROM users")){if(rs.next())return rs.getInt(1);}catch(SQLException e){logger.log(Level.SEVERE,"count",e);}return 0;}
    private User map(ResultSet rs)throws SQLException{return new User(rs.getInt("user_id"),rs.getString("full_name"),rs.getString("username"),rs.getString("email"),rs.getString("password_hash"),rs.getString("phone"),rs.getString("role"),rs.getString("status"),rs.getTimestamp("created_at"),rs.getTimestamp("updated_at"));}
}
