package com.smartkyc.dao;
import com.smartkyc.database.ConnectionFactory;
import com.smartkyc.model.ValidationRecord;
import java.sql.*;
import java.util.*;
import java.util.logging.*;
public class ValidationHistoryDAOImpl implements ValidationHistoryDAO {
    private static final Logger logger=Logger.getLogger(ValidationHistoryDAOImpl.class.getName());
    @Override public List<ValidationRecord> findAll(){List<ValidationRecord> l=new ArrayList<>();try(Connection c=ConnectionFactory.getConnection();Statement s=c.createStatement();ResultSet rs=s.executeQuery("SELECT * FROM validation_history ORDER BY validated_at DESC")){while(rs.next())l.add(map(rs));}catch(SQLException e){logger.log(Level.SEVERE,"findAll",e);}return l;}
    @Override public List<ValidationRecord> findByFilters(String search,String docType,String status){List<ValidationRecord> l=new ArrayList<>();StringBuilder sql=new StringBuilder("SELECT * FROM validation_history WHERE 1=1");List<String> params=new ArrayList<>();if(search!=null&&!search.isEmpty()){sql.append(" AND document_number LIKE ?");params.add("%"+search+"%");}if(docType!=null&&!docType.isEmpty()&&!"All".equals(docType)){sql.append(" AND document_type=?");params.add(docType);}if(status!=null&&!status.isEmpty()&&!"All".equals(status)){sql.append(" AND status=?");params.add(status);}sql.append(" ORDER BY validated_at DESC");try(Connection c=ConnectionFactory.getConnection();PreparedStatement ps=c.prepareStatement(sql.toString())){for(int i=0;i<params.size();i++)ps.setString(i+1,params.get(i));try(ResultSet rs=ps.executeQuery()){while(rs.next())l.add(map(rs));}}catch(SQLException e){logger.log(Level.SEVERE,"findByFilters",e);}return l;}
    @Override public boolean insert(ValidationRecord r){String sql="INSERT INTO validation_history(user_id,document_type,document_number,status,reason)VALUES(?,?,?,?,?)";try(Connection c=ConnectionFactory.getConnection();PreparedStatement ps=c.prepareStatement(sql)){ps.setInt(1,r.getUserId());ps.setString(2,r.getDocumentType());ps.setString(3,r.getDocumentNumber());ps.setString(4,r.getStatus());ps.setString(5,r.getReason());return ps.executeUpdate()>0;}catch(SQLException e){logger.log(Level.SEVERE,"insert",e);}return false;}
    @Override public boolean delete(int id){try(Connection c=ConnectionFactory.getConnection();PreparedStatement ps=c.prepareStatement("DELETE FROM validation_history WHERE validation_id=?")){ps.setInt(1,id);return ps.executeUpdate()>0;}catch(SQLException e){logger.log(Level.SEVERE,"delete",e);}return false;}
    @Override public boolean clearAll(){try(Connection c=ConnectionFactory.getConnection();Statement s=c.createStatement()){s.executeUpdate("DELETE FROM validation_history");return true;}catch(SQLException e){logger.log(Level.SEVERE,"clearAll",e);}return false;}
    @Override public int getTotalValidationsCount(){try(Connection c=ConnectionFactory.getConnection();Statement s=c.createStatement();ResultSet rs=s.executeQuery("SELECT COUNT(*) FROM validation_history")){if(rs.next())return rs.getInt(1);}catch(SQLException e){logger.log(Level.SEVERE,"count",e);}return 0;}
    @Override public int getTodayValidationsCount(){try(Connection c=ConnectionFactory.getConnection();Statement s=c.createStatement();ResultSet rs=s.executeQuery("SELECT COUNT(*) FROM validation_history WHERE DATE(validated_at)=CURDATE()")){if(rs.next())return rs.getInt(1);}catch(SQLException e){logger.log(Level.SEVERE,"todayCount",e);}return 0;}
    @Override public int getCountByDocAndStatus(String dt,String st){try(Connection c=ConnectionFactory.getConnection();PreparedStatement ps=c.prepareStatement("SELECT COUNT(*) FROM validation_history WHERE document_type=? AND status=?")){ps.setString(1,dt);ps.setString(2,st);try(ResultSet rs=ps.executeQuery()){if(rs.next())return rs.getInt(1);}}catch(SQLException e){logger.log(Level.SEVERE,"countByDocStatus",e);}return 0;}
    @Override public List<ValidationRecord> findRecent(int limit){List<ValidationRecord> l=new ArrayList<>();try(Connection c=ConnectionFactory.getConnection();PreparedStatement ps=c.prepareStatement("SELECT * FROM validation_history ORDER BY validated_at DESC LIMIT ?")){ps.setInt(1,limit);try(ResultSet rs=ps.executeQuery()){while(rs.next())l.add(map(rs));}}catch(SQLException e){logger.log(Level.SEVERE,"findRecent",e);}return l;}
    private ValidationRecord map(ResultSet rs)throws SQLException{return new ValidationRecord(rs.getInt("validation_id"),rs.getInt("user_id"),rs.getString("document_type"),rs.getString("document_number"),rs.getString("status"),rs.getString("reason"),rs.getTimestamp("validated_at"));}
}
