db.url=jdbc:mysql://localhost:3306/KYCValidatorDB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
db.username=root
db.password=root
app.name=SmartKYC
app.version=1.0.0
app.theme=dark
app.log.path=logs/application.log
